<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.com.agileware.elections/xml/schema/CRM/Elections/ElectionVote.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c88d37e6f97aa71c3f63281c2b6b03d1)
 */
use CRM_Elections_ExtensionUtil as E;

/**
 * Database access object for the ElectionVote entity.
 */
class CRM_Elections_DAO_ElectionVote extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_election_vote';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ElectionVote ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Rank of a nomination for particular position.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $rank;

  /**
   * FK to ElectionNomination for which this vote is counted.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $election_nomination_id;

  /**
   * FK to Contact who added this vote.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $member_id;

  /**
   * Date on which vote has been added.
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_at;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_election_vote';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Election Votes') : E::ts('Election Vote');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_nomination_id', 'civicrm_election_nomination', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'member_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ElectionVote ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_vote.id',
          'table_name' => 'civicrm_election_vote',
          'entity' => 'ElectionVote',
          'bao' => 'CRM_Elections_DAO_ElectionVote',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '5.3',
        ],
        'rank' => [
          'name' => 'rank',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Rank'),
          'description' => E::ts('Rank of a nomination for particular position.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_vote.rank',
          'export' => TRUE,
          'table_name' => 'civicrm_election_vote',
          'entity' => 'ElectionVote',
          'bao' => 'CRM_Elections_DAO_ElectionVote',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'election_nomination_id' => [
          'name' => 'election_nomination_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Election Nomination ID'),
          'description' => E::ts('FK to ElectionNomination for which this vote is counted.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_vote.election_nomination_id',
          'table_name' => 'civicrm_election_vote',
          'entity' => 'ElectionVote',
          'bao' => 'CRM_Elections_DAO_ElectionVote',
          'localizable' => 0,
          'FKClassName' => 'CRM_Elections_DAO_ElectionNomination',
          'add' => '5.3',
        ],
        'member_id' => [
          'name' => 'member_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Member ID'),
          'description' => E::ts('FK to Contact who added this vote.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_vote.member_id',
          'table_name' => 'civicrm_election_vote',
          'entity' => 'ElectionVote',
          'bao' => 'CRM_Elections_DAO_ElectionVote',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '5.3',
        ],
        'created_at' => [
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created At'),
          'description' => E::ts('Date on which vote has been added.'),
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_vote.created_at',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_election_vote',
          'entity' => 'ElectionVote',
          'bao' => 'CRM_Elections_DAO_ElectionVote',
          'localizable' => 0,
          'add' => '5.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'election_vote', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'election_vote', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
