<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.com.agileware.elections/xml/schema/CRM/Elections/ElectionNomination.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:69228fe2e9c1bf91c3f2e4e01c77dc84)
 */
use CRM_Elections_ExtensionUtil as E;

/**
 * Database access object for the ElectionNomination entity.
 */
class CRM_Elections_DAO_ElectionNomination extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_election_nomination';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ElectionNomination ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $comments;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $rejection_comments;

  /**
   * Boolean field to identity if nomination is a valid candidate.
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_eligible_candidate;

  /**
   * Boolean field to identity if nomination has been accepted by candidate.
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $has_accepted_nomination;

  /**
   * Boolean field to identity if nomination has been rejected by candidate.
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $has_rejected_nomination;

  /**
   * Date on which election nomination created.
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_at;

  /**
   * Date on which election nomination was updated.
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $updated_at;

  /**
   * FK to Contact for which this nomination is added.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $member_nominee;

  /**
   * FK to ElectionPosition for which this nomination is added.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $election_position_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_election_nomination';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Election Nominations') : E::ts('Election Nomination');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'member_nominee', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_position_id', 'civicrm_election_position', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ElectionNomination ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_nomination.id',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '5.3',
        ],
        'comments' => [
          'name' => 'comments',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Comments'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_nomination.comments',
          'export' => TRUE,
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'rejection_comments' => [
          'name' => 'rejection_comments',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Rejection Comments'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_nomination.rejection_comments',
          'export' => TRUE,
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'is_eligible_candidate' => [
          'name' => 'is_eligible_candidate',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Eligible Candidate'),
          'description' => E::ts('Boolean field to identity if nomination is a valid candidate.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_nomination.is_eligible_candidate',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => '5.3',
        ],
        'has_accepted_nomination' => [
          'name' => 'has_accepted_nomination',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Has Accepted Nomination'),
          'description' => E::ts('Boolean field to identity if nomination has been accepted by candidate.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_nomination.has_accepted_nomination',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => '5.3',
        ],
        'has_rejected_nomination' => [
          'name' => 'has_rejected_nomination',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Has Rejected Nomination'),
          'description' => E::ts('Boolean field to identity if nomination has been rejected by candidate.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_nomination.has_rejected_nomination',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => '5.3',
        ],
        'created_at' => [
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created At'),
          'description' => E::ts('Date on which election nomination created.'),
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_nomination.created_at',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'add' => '5.3',
        ],
        'updated_at' => [
          'name' => 'updated_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Updated At'),
          'description' => E::ts('Date on which election nomination was updated.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_nomination.updated_at',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'add' => '5.3',
        ],
        'member_nominee' => [
          'name' => 'member_nominee',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Member Nominee'),
          'description' => E::ts('FK to Contact for which this nomination is added.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_nomination.member_nominee',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '5.3',
        ],
        'election_position_id' => [
          'name' => 'election_position_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Election Position ID'),
          'description' => E::ts('FK to ElectionPosition for which this nomination is added.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_nomination.election_position_id',
          'table_name' => 'civicrm_election_nomination',
          'entity' => 'ElectionNomination',
          'bao' => 'CRM_Elections_DAO_ElectionNomination',
          'localizable' => 0,
          'FKClassName' => 'CRM_Elections_DAO_ElectionPosition',
          'add' => '5.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'election_nomination', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'election_nomination', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
