<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.com.agileware.elections/xml/schema/CRM/Elections/ElectionResult.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:6b2336c600e84b016ce474742d1568d6)
 */
use CRM_Elections_ExtensionUtil as E;

/**
 * Database access object for the ElectionResult entity.
 */
class CRM_Elections_DAO_ElectionResult extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_election_result';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ElectionResult ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Rank of a member for particular position.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $rank;

  /**
   * FK to ElectionPosition for which this result is added.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $election_position_id;

  /**
   * FK to ElectionNomination for which this rank is added.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $election_nomination_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_election_result';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Election Results') : E::ts('Election Result');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_position_id', 'civicrm_election_position', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_nomination_id', 'civicrm_election_nomination', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ElectionResult ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_result.id',
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '5.3',
        ],
        'rank' => [
          'name' => 'rank',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Rank'),
          'description' => E::ts('Rank of a member for particular position.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_result.rank',
          'export' => TRUE,
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'election_position_id' => [
          'name' => 'election_position_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Election Position ID'),
          'description' => E::ts('FK to ElectionPosition for which this result is added.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_result.election_position_id',
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'FKClassName' => 'CRM_Elections_DAO_ElectionPosition',
          'add' => '5.3',
        ],
        'election_nomination_id' => [
          'name' => 'election_nomination_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Election Nomination ID'),
          'description' => E::ts('FK to ElectionNomination for which this rank is added.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_result.election_nomination_id',
          'table_name' => 'civicrm_election_result',
          'entity' => 'ElectionResult',
          'bao' => 'CRM_Elections_DAO_ElectionResult',
          'localizable' => 0,
          'FKClassName' => 'CRM_Elections_DAO_ElectionNomination',
          'add' => '5.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'election_result', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'election_result', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
