<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.com.agileware.elections/xml/schema/CRM/Elections/ElectionPosition.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a13f32d1c31241d49f780e13f969c20b)
 */
use CRM_Elections_ExtensionUtil as E;

/**
 * Database access object for the ElectionPosition entity.
 */
class CRM_Elections_DAO_ElectionPosition extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '5.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_election_position';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ElectionPosition ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Name of the position.
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Quantity of a this position.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $quantity;

  /**
   * Order of a this position.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sortorder;

  /**
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Date on which election position created.
   *
   * @var string|null
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_at;

  /**
   * Date on which election position was updated.
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $updated_at;

  /**
   * FK to Election
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $election_id;

  /**
   * FK to Contact who created particular position
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_by;

  /**
   * Result status for this position.
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $result_status;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_election_position';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Election Positions') : E::ts('Election Position');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'election_id', 'civicrm_election', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'created_by', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique ElectionPosition ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_position.id',
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '5.3',
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Name of the position.'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_position.name',
          'export' => TRUE,
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'quantity' => [
          'name' => 'quantity',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Quantity'),
          'description' => E::ts('Quantity of a this position.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_position.quantity',
          'export' => TRUE,
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'sortorder' => [
          'name' => 'sortorder',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Sortorder'),
          'description' => E::ts('Order of a this position.'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_position.sortorder',
          'export' => TRUE,
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_position.description',
          'export' => TRUE,
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
        'created_at' => [
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created At'),
          'description' => E::ts('Date on which election position created.'),
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_position.created_at',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'add' => '5.3',
        ],
        'updated_at' => [
          'name' => 'updated_at',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Updated At'),
          'description' => E::ts('Date on which election position was updated.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_position.updated_at',
          'export' => TRUE,
          'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'add' => '5.3',
        ],
        'election_id' => [
          'name' => 'election_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Election ID'),
          'description' => E::ts('FK to Election'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_position.election_id',
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'FKClassName' => 'CRM_Elections_DAO_Election',
          'add' => '5.3',
        ],
        'created_by' => [
          'name' => 'created_by',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Created By'),
          'description' => E::ts('FK to Contact who created particular position'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_election_position.created_by',
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '5.3',
        ],
        'result_status' => [
          'name' => 'result_status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Result Status'),
          'description' => E::ts('Result status for this position.'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_election_position.result_status',
          'export' => TRUE,
          'table_name' => 'civicrm_election_position',
          'entity' => 'ElectionPosition',
          'bao' => 'CRM_Elections_DAO_ElectionPosition',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'election_position', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'election_position', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
