-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
---- /*******************************************************
-- *
-- * Clean up the existing tables-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_election_vote`;
DROP TABLE IF EXISTS `civicrm_election_result`;
DROP TABLE IF EXISTS `civicrm_election_nomination_seconder`;
DROP TABLE IF EXISTS `civicrm_election_nomination`;
DROP TABLE IF EXISTS `civicrm_election_position`;
DROP TABLE IF EXISTS `civicrm_election`;

SET FOREIGN_KEY_CHECKS=1;